[project]
name = "sipit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fire>=0.7.1",
    "jupyter>=1.1.1",
    "ruff>=0.14.3",
    "torch>=2.9.0",
    "transformers>=4.57.1",
]
